### ISSUE TITLE
Best practices for CEP when building panels that support multiple versions of Photoshop?

### ISSUE THREAD

**Issue by willworkforhugs** [Adobe-CEP/CEP-Resources#17]
Given the mix of CEP versions out there for html5 panels, I'm curious as to how others are approaching integration (for simple panels, nothing fancy)?  Are you using a single version of CEP to support CC through CC 2015, or doing multiple builds of your panels for each version?

**Comment by arthurwei1975** [comment]
We try our best to make each CEP release backward compatible. That is to say, we add features, but we rarely remove/change features. (But we did remove/change some features due to various reasons.)

Therefore, it is possible to develop one extension and run in multiple CEP versions. You may need to detect CEP or host application's version, and write some specific code for a specific version.

If the extension is too fancy, it is also a good idea to have multiple builds for multiple CEP major versions (also Creative Cloud major versions).

Thanks

**Comment by gregbenz** [comment]
Thanks.  You don't happen to have such open source code to help manage
multiple CEP versions, do you?

On Tue, Jul 7, 2015 at 5:13 PM, GUO WEI <notifications@github.com> wrote:

> We try our best to make each CEP release backward compatible. That is to
> say, we add features, but we rarely remove/change features. (But we did
> remove/change some features due to various reasons.)
>
> Therefore, it is possible to develop one extension and run in multiple CEP
> versions. You may need to detect CEP or host application's version, and
> write some specific code for a specific version.
>
> If the extension is too fancy, it is also a good idea to have multiple
> builds for multiple CEP major versions (also Creative Cloud major versions).
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Adobe-CEP/CEP-Resources/issues/17#issuecomment-119359080>
> .
>



-- 
================================
*Greg Benz Photography*
612-568-8742
www.GregBenzPhotography.com <http://www.gregbenzphotography.com/>
Represented by Getty Images <http://artist.gettyimages.com/link/5362993>
================================

**Comment by arthurwei1975** [comment]
No, we do not have.
