### ISSUE TITLE
Unable to build a valid certificate chain

### ISSUE THREAD

**Issue by michaeljweaver** [Adobe-CEP/CEP-Resources#21]
As extension manager is now at it's end of life I'm trying to publish my CEP plugin to the Add Ons website.
When I try and do this I get the error: 
"Ensure your ZXP has been signed with a certificate which will not expire in the next 8 years, or add a timestamp to your signature."

I was previously signing my plugin with an older version of zxpsigncmd and not using the -tsa argument. (However zxpsigncmd was able to package my plugin successfully using a certificate). 
So in order to publish the plugin, I added -tsa https://timestamp.geotrust.com/tsa. When I ran zxpsigntool with this command I get the following error "Error - the timestamp returned from the chosen TSA could not be verified, so the ZXP created is likely to be rejected by other tools. Please recreate your ZXP with a different trusted TSA."

I tried a number of other tsa's with no luck. So I did a bit of googling and found a similar issue which suggested to download a later version of zxpsigntool from this repository, which I did.
With this version of zxpsigntool I get the following error whether I use the -tsa option or not - "Unable to build a valid certificate chain. Please make sure that all certificates are included in the certificate file."

The certificate I'm trying to use is issued by a trusted authority (GlobalSign). I made sure I followed the process defined here - https://forums.adobe.com/thread/698683

Any help would be greatly appreciated.

**Comment by fgregor** [comment]
I think you might be seeing the same issue as the user in this forum thread: https://forums.adobe.com/thread/1570506

The user there was able to solve the issue by exporting his GlobalSign certificate via Mozilla Firefox - would you be able to try this?

Another more complex approach to try if all else fails (on Mac):
• Using terminal – where “original.p12” is the P12 file causing problems:
•  openssl pkcs12 –in original.p12 –out original.pem
       entering the same password whenever prompted
• Open original.pem in a text editor (see attached for example original.pem before changes made – notice that the root certificate is second, rather than first in the chain)
• Cut-paste certificate sections into the correct order, starting from “Bag Attributes” until “-----END CERTIFICATE-----”
• After reordering, the first certificate’s subject should be identical to the issuer
• Each subsequent certificate’s issuer should match the subject of the certificate above
• Save the re-ordered file as reordered.pem (see attached for example reordered.pem – notice that the      root certificate is now first in the chain)
• openssl pkcs12 –export –in reordered.pem –out reordered.p12
      entering the same password as before, whenever prompted
•  Then you should be able to use reordered.p12 in place of “original.p12”

**Comment by michaeljweaver** [comment]
Yep that worked!

Initially Firefox was not able to import my certificate. It seems this is a problem with recent Firefox builds - http://forums.mozillazine.org/viewtopic.php?f=38&t=2867963

So I rolled back to Firefox 30 and then was able to import and export my certificate. Now the new version of zxpsigntool works fine with the -tsa option as well.

Thanks for your help!

**Comment by fgregor** [comment]
That's great, thanks for letting me know!
