### ISSUE TITLE
Node.js version update?

### ISSUE THREAD

**Issue by undavide** [Adobe-CEP/CEP-Resources#22]
Hi,
I've checked the node.js version inside Photoshop (the one used by Generator) and it's version 0.10.37, while node used in CEP extensions (process.version) is 0.8.22 - quite old compared to latest 12.7.
Is there any information that you can share about the update roadmap?
Thank you,

-Davide

**Comment by arthurwei1975** [comment]
Yes, we will update Node.js in CEP in the upcoming Creative Cloud release. Thanks

**Comment by itsmeonline** [comment]
Useful question David.
Good Node.JS update is coming :)

**Comment by undavide** [comment]
Hi @arthurwei1975,
apparently I've been living in a cave since I wasn't aware that the merge of the two branches of `node.js` and `io.js` has resulted in a new versioning - i.e. Node (one and only) is now 4.x and relies on an updated version of Google V8 (as seen [here](http://apmblog.dynatrace.com/2015/09/05/all-you-need-to-know-about-node-js-4-0/)). Should we expect that this would land on CEP?
Thank you,

-Davide

**Comment by arthurwei1975** [comment]
Not in the upcoming release. But we will investigate it and hopefully pick up it in next release in 2016. Thanks

**Comment by undavide** [comment]
Thanks Arthur, please keep this one as a feature request :-)

**Comment by itsmeonline** [comment]
Appreciate this issue is closed, however can @arthurwei1975 @undavide  or anyone confirm the latest Node version shipped in cc2017? We have legacy extensions requiring support for cc2015 (PP), which uses Node version: v0.8.22 (Note: our extension requires use of webWorkers too). 

For this and other related reasons, I am trying to determine what Node version is currently being used? e.g. in latest and greatest current release?
Thanks in advance!

**Comment by undavide** [comment]
Hi,
if you want to check the exact version of Node.js that CEF uses, just log `process.version`.
Hope this helps,
Davide
