### ISSUE TITLE
Moving to a more recent version of WebKit/Chrome

### ISSUE THREAD

**Issue by AndrewMore1** [Adobe-CEP/CEP-Resources#28]
Currently it appears that the browser being used internally on MacOS versions of CC 2015 Adobe applications is Chrome 27.  Are there any plans to update this to a later version of Chrome/WebKit?

**Comment by arthurwei1975** [comment]
Yes, it will be upgraded to newer version in the upcoming CC 2015 update release.

**Comment by AndrewMore1** [comment]
Can you provide details on what version of Chrome, and when the release will be?  In particular I need support for Flexbox as currently supported by Chrome.

**Comment by arthurwei1975** [comment]
It will be Chromium 41.0.2272.104. We use CEF, which is based on Chromium.

**Comment by AndrewMore1** [comment]
Has the move to Chromim 41.0.2272.104 or later happened yet?
Thanks!

**Comment by Jolg42** [comment]
I don't know what they've did but the remote debugging is now bugged! You can't scroll anymore in the remote inspector in 2015.2 release, the issue is here [Chromium Issue 516760 : Can't scroll in DevTools console](https://code.google.com/p/chromium/issues/detail?id=516760)

So the fix is to put the missing css like this :
```js
(function() {
  var styleElement = document.createElement("style");
  styleElement.type = "text/css";
  styleElement.textContent = "html /deep/ * { min-width: 0; min-height: 0; }";
  document.head.appendChild(styleElement);
})();
``` 
Happy debugging! :beetle:

**Comment by alexwidener** [comment]
I'm having the same issue as @Jolg42 on both OS X 10.10.x and Windows 7 with Chrome.
Except it's with 2015.1, the release that just came out. This feature was not busted before 2015.1, worked fine in 2014 and 2015.0.
