### ISSUE TITLE
CEP10 node-soap breaks on Windows

### ISSUE THREAD

**Issue by schmarre** [Adobe-CEP/CEP-Resources#328]
Having an issue on CC Indesign extension on the newly released CEP10 on windows.
The extension communicates with a backend through web-services (wsdl) using node-soap module. 
This extension has been working for about 8 years without any problems, on windows and mac osx. 
Testing the extension on the new Indesign 2021 release, the windows extension breaks when trying to connect to the web-service.
Following error message can be seen:
<code>
_http_outgoing.js:764 Uncaught TypeError: socket.cork is not a function
    at ClientRequest._flushOutput (_http_outgoing.js:764)
    at ClientRequest._flush (_http_outgoing.js:746)
    at _http_client.js:294
    at callSocketMethod (_http_client.js:732)
    at ClientRequest.onSocket (_http_client.js:737)
    at Object.onceWrapper (VM73 events.js:288)
    at ClientRequest.emit (VM73 events.js:205)
    at tickOnSocket (_http_client.js:676)
    at onSocketNT (_http_client.js:715)
    at processTicksAndRejections (VM84 task_queues.js:103)
</code>

Extension deployed on Mac OSX works fine in Indesign 2021!

This extension is being applied in production environments handling classifieds workflow. Any checkup and advice would be greatly appreciated.
Thanks in advance

**Comment by sujaisivanandan** [comment]
@schmarre 

This is one of the Issues seen on NWJS version 0.38 will also be applicable in CEP 10(Since we have update to NodeJS v12)
For example: There are errors noticed when node module "winston" is used with any other node module which uses duplex. **Workaround which we saw in NWJS forums:** In case you are using the node module "winston" please add this below script to the extension.

Adding this script to the extension solves the issue.
`var {Duplex} = require('stream')
var {Writable} = require('stream')
{
  // Allow the keys array to be GC'ed.
  const keys = Object.keys(Writable.prototype);
  for (var v = 0; v < keys.length; v++)

{     const method = keys[v];     if (!Duplex.prototype[method])       Duplex.prototype[method] = Writable.prototype[method];   
}`


Also refer this on CEP 10 migration guides: https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_10.x/Documentation/CEP%2010.0%20HTML%20Extension%20Cookbook.md#migration-from-cep-9-to-cep-10

Hope this helps!

**Comment by schmarre** [comment]
@sujaisivanandan 
Thanks for your quick answer.
I've added the script to the extension and it now works.

Thanks
