### ISSUE TITLE
Need help figuring out the api

### ISSUE THREAD

**Issue by navanshu** [Adobe-CEP/CEP-Resources#348]
I am making a plugin for photoshop, I am confused about the api, I want to know the location of active file. Please guide me to the correct documentation and similar api. I checked CSInterface but couldn't find anything similar.
Thanks

**Comment by ErinFinnegan** [comment]
Which Photoshop API are you trying to use? I'd guess CEP, since you reference CSInterface... have you seen the following resources?

- https://www.adobe.io/photoshop/ 
- https://www.adobe.io/photoshop/uxp/
- https://github.com/Adobe-CEP/Samples/blob/master/PhotoshopEvents/host/ps.jsx
- https://www.adobe.com/content/dam/acom/en/devnet/photoshop/pdfs/photoshop-scripting-guide-2020.pdf
 (which is from: https://www.adobe.com/devnet/photoshop/scripting.html )

**Comment by Inventsable** [comment]
CSInterface doesn't have access to the document, it only has general properties about the app you're working in (what the app name is, current theme data, OS and environment, locale, etc). To get particular information about the document you have to use `evalScript` via CSInterface to some DOM property like `app.activeDocument.path`, which will return the filepath of the document (though be warned, it causes a syntax error on files which aren't saved so it's not as well implemented as you'd expect). [Here's a link to the Photoshop DOM for scripting](https://www.indesignjs.de/extendscriptAPI/photoshop2015.5/#about.html).

**Comment by navanshu** [comment]
I am pretty new and was planning to use Adobe CEP for building a photoshop plugin but then I found Adobe UXP development seems simpler when using UXP.
