### ISSUE TITLE
ExtendScript call fails on Illustrator 25.3.1 beta (macOS) using CEP 11

### ISSUE THREAD

**Issue by zhangusc** [Adobe-CEP/CEP-Resources#357]
Update to Illustrator Beta 25.3.1 on both Windows and macOS. Our extension works well on Windows but fails to launch on macOS (debug mode). Check out the CEP version of Illustrator and found out Illustrator Beta 25.3.1 (Windows) uses CEP 10.2 while Illustrator Beta 25.3.1 (macOS) uses CEP 11.  @ErinFinnegan  Is this something expected?

**Comment by sujaisivanandan** [comment]
Hi @zhangusc ,
CEP 11 is our the upcoming version where CEP extensions will have native Mac ARM support. This version is expected and soon windows also will be updated to CEP 11.

Can you provide the details of the extension that is failing? I can investigate this issue.
Also can you elaborate what you mean by debug mode.

**Comment by zhangusc** [comment]
Hi @sujaisivanandan Thank you for the quick response.  The original issue was found in debug mode.  The released version of our app runs fine in non-debug mode. It is a little surprise to see a major CEP update on a minor/patch Adobe app (Illustrator) update, especially when the underlying chromium version of CEP 11 stays the same 74.0.3729.157 as CEP 10. Any announcement and documentation of CEP 11 that I can know more about it?

**Comment by ErinFinnegan** [comment]
According to the notes I've got... CEP 11.1 will have CEF 3 release branch - (88). The inclusion of CEP 11 in Illustrator beta (only for M1 macOS) is a bit of a surprise.

I haven't done a major announcement other than a brief mention in [this blog post](https://medium.com/adobetech/photoshop-plugin-support-for-apple-silicon-required-recompile-for-c-plugins-efadd3ea0096?source=friends_link&sk=a921c05069f31d3ac4daa13ed2189659) and in [the developer newsletter](https://adobeint-mkt-prod1-m.campaign.adobe.com/rest/head/mirrorPage/@yzGCMDacLWMhu42LzuizF0jMsrW4VaK-KmpEB7EhFRxsS77yVe2meS812LfjatUcnuBxg5l764u_qP47NmfYeoCEFTKJRJqmVzEKUvsDRJtvRLTk.html). (Note that link will only work for a month or so, anyone hoping to subscribe, please[ subscribe here](https://www.adobe.com/subscription/ccdevnewsletter.html).)

More announcements will follow on the Adobe Tech Blog and in the Developer newsletter.

**Comment by sujaisivanandan** [comment]
CEP 11.0 is an interim build that helps Apps like Illustrator and Indesign to pre-release the Native ARM support on Apple M1 devices. This build still has CEPhtmlEngine running in emulation mode thought the App is running natively as an ARM application. As Erin mentioned, CEP 11.1 will have CEF upgraded to v88 and CEPHTMLEngine will also run as a native arm process. Do watch for the beta/pre-release builds of Illustrator and InDesign with CEP 11.1 and let us know your feedback.

**Comment by zhangusc** [comment]
@sujaisivanandan We also encountered an error on Illustrator 25.3.1 beta (macOS) reported here https://forums.adobeprerelease.com/illustratorpr/discussion/2850. Basically, the code `new ExternalObject('lib:AdobeXMPScript') ` in jsx script fails. The same code runs fine in Illustrator 25.3.1 beta (Windows). Do you think it is related to this CEP 11 update?

**Comment by zhangusc** [comment]
@ErinFinnegan @sujaisivanandan Any ideas about the failure of `new ExternalObject('lib:AdobeXMPScript') ` on Illustrator 25.3.1 Beta (macOS)? Is it an Illustrator issue or a CEP11 issue?

**Comment by sujaisivanandan** [comment]
Hi @zhangusc, Still investigating this, there has been changes on both Illustrator and CEP side. Will get back on this.

**Comment by zhangusc** [comment]
@sujaisivanandan @ErinFinnegan Thank you. It is a critical issue and a show stopper for ArcGIS Maps for Adobe Creative Cloud extension. Want to follow up with your folks to make sure it gets addressed before Illustrator 25.3 public release.

**Comment by zhangusc** [comment]
@ErinFinnegan @sujaisivanandan Do you have any updates to share on this issue?

**Comment by sujaisivanandan** [comment]
This is a regression and will be fixed before the 25.3 public release 
tracking ID : AI-4247491

**Comment by zhangusc** [comment]
@sujaisivanandan I have seen this Alert when I launch our CEP extension in Illustrator (Windows). What does it mean?
![image](https://user-images.githubusercontent.com/7468979/119059066-6f5b2d00-b984-11eb-9ca9-1ebeaee4f230.png)

**Comment by sujaisivanandan** [comment]
You can ignore this assert. This will be removed in the final production build.

Hope you can try out your CEP extensions on this build!

**Comment by zhangusc** [comment]
@sujaisivanandan Our extension failed on the latest prerelease (macOS version). In debug console, I have seen multiple new "ingest" requests sent by CEP, and one of the "ingest" requests failed/stalled, which causes the problem. Any idea?

 BTW, the Windows version seems working fine.

**Comment by sujaisivanandan** [comment]
@zhangusc the CEF version has been updated and there can be some in-compatibilty. Can you check the debug console for any errors?

**Note on some of the known changes for Migration from CEP 10 to CEP 11 due to new CEF**

1. Update the Node Modules: CEP 11 works with NodeJS 15.9.0 and Node-WebKit 0.50.1 versions. If extensions were build on older version of NodeJS there can be cases where these extensions may not load in CEP 11 due to incompatible node modules. In such cases, the node modules need to be updated using NodeJS version 15.9.0 or higher.

2. Content-Security-Policy Changes: With CEP 11.1 that integrates CEF #88, content-security-policy checks have been enforced strictly. Extensions that embed third-party sites may not be able to do so anymore if the site that is being embedded has a content-security-policy directive that doesn't allow sites to frame them.

3. Cookies: With #CEF v88 version, we have seen that when no SameSite attribute is set in a cookie, it defaults to SameSite=Lax. This will cause the cookie to be blocked in cross-site contexts. If your application needs cookies to be used in a cross-site context, we suggest you set SameSite=None.If component is not sending SameSite attribute in the cookie it would default to SameSite=Lax for preventing to set the cookie in cross-site context.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite

4.CORS checks: With CEP 11, with security updates, we are seeing that a lot more requests are being blocked by CORS checks. The extension may encounter this if it is trying to access an endpoint that does not have the Access-Control-Allow-Origin header. Please ensure that the endpoints that are being accessed have Access-Control-Allow-Origin headers set appropriately.

**Comment by zhangusc** [comment]
@sujaisivanandan @ErinFinnegan 
Apparently, the Content-Security-Policy and CORS changes have significant impacts on our extension. At the first glance, I see our users' login experience to the extension is broken on Illustrator 25.3 prerelease. Moving from CEP 10 to 11 with the CEF upgrade from v74 to v88 is a big jump.  I wonder if the CEP 11 is going to be released as a minor release on the top of Illustrator 25.x (2021) or it is something planned for this year's Adobe Max release Illustrator 26 (2022)?  

@sujaisivanandan Our extension is not available on Adobe Exchange, you can download it from our product page https://www.esri.com/en-us/arcgis/products/maps-for-adobecc/overview.  Please try it out and let me know what you think. Thx

**Comment by sujaisivanandan** [comment]
Illustrator 25.3 and Indesign 16.3 are releasing with CEP 11 soon, since this release is mainly targeting native apple silicon support. Update CEF to 88 is needed for this arm support. Other apps will follow to integrate CEP subsequently by MAX.


I'll take a look at your plugin but the changes for Content-Security-Policy and CORS changes on Extension side would be needed.

**Comment by sujaisivanandan** [comment]
Hi @zhangusc  I am able to load the extension and see only some syntax errors.
![Screenshot 2021-05-26 at 3 35 40 PM](https://user-images.githubusercontent.com/57343729/119648639-54366480-be3f-11eb-8609-7659736a23b5.png).

Am trying this on the latest Illustrator builds.

**Comment by zhangusc** [comment]
Hi @sujaisivanandan Thanks a lot for looking into it. The issue occurs on users' sign-in experience.  Click "ArcGIS Online" on the screenshot and you will receive an oAuth sign-in page. Could you please send a msg to me at xzhang@esri.com? I will send you a login credential for testing.

**Comment by int255** [comment]
We have similar issue after installer AI Prerelease 25.3/CEF 11, CORS policy blocked javascript API call from outer frame to inner frame (different domain).

@Adobe Please consider to keep CORS policy same as CEF 10 or earlier, since this will break existing CEP extension applications that already took advantage of old (weak) CORS policy. Bottom line, please at least make CORS policy configurable in the CSXS manefest.xml

**Comment by sujaisivanandan** [comment]
@int255 these are security features and CEF/Chromium has been making this more strict compared to earlier versions. It will be difficult to make this configurable in the manifest since CEF does not provide these are configurable options.

I do understand that this breaks your plugin and leads to additional work to update, however do note that this helps with the improved security for the user.

**Comment by sujaisivanandan** [comment]
@zhangusc can you check if the details mentioned in https://github.com/Adobe-CEP/CEP-Resources/issues/364 would help in your case?

**Comment by zhangusc** [comment]
> This is a regression and will be fixed before the 25.3 public release
> tracking ID : AI-4247491

@ErinFinnegan @sujaisivanandan Could you please check the status of **AI-4247491**? The failure of `new ExternalObject('lib:AdobeXMPScript') ` was not reproducible in Illustrator 25.3.1 (macOS). but now resurfaces on the latest Illustrator 25.4.1(macOS).  This is a showstopper for our extension to run on the latest Illustrator. Any solution/workaround is appreciated.

**Comment by danh525** [comment]
Any update on when this will be addressed? I have customers in production that can't upgrade because of this bug!

**Comment by sujaisivanandan** [comment]
The issue has been fixed and you should see this in the next Illustrator pre-release(v26.0).

**Comment by ErinFinnegan** [comment]
Hi @zhangusc ! 26 is posted in the prerelease today if you want to take a look...

**Comment by danh525** [comment]
The link in the prerelease forum doesn't provide a download link; can you
provide a link to actually download the software?

**Comment by ErinFinnegan** [comment]
I think so... this is [the Mac download](https://download.adobeprerelease.com/85A6F544-2705-49BD-8314-DD549C6A1713/1632147315/AI_2022_SDK_Mac.dmg?programID=85A6F544-2705-49BD-8314-DD549C6A1713&assetID=14C46C34-49D3-4823-FF91-5E2457723014&_=1632161126460) (login required).

Or, you can go to [the downloads section here](https://www.adobeprerelease.com/beta/85A6F544-2705-49BD-8314-DD549C6A1713#tab_downloads).

I'd also recommend looking for it in the Creative Cloud Desktop app, if you use it:

<img width="1024" alt="Screen Shot 2021-09-20 at 2 08 05 PM" src="https://user-images.githubusercontent.com/2728504/134052470-d914a485-156a-4582-a07c-96014d02ee4d.png">

**Comment by danh525** [comment]
The "mac download" has SDK in the file name - is it Illustrator or just the
SDK? I need Illustrator.

The "downloads section here" doesn't contain a download link; has a link to
instructions which takes you to a forum but no download.

My CC Desktop app doesn't include beta versions; how do I get those to show
up?

Why is this so hard?

**Comment by ErinFinnegan** [comment]
> My CC Desktop app doesn't include beta versions; how do I get those to show
> up?

Hopefully you can go the the CC Desktop app and go to Help -> Check for Updates, and update to version 5.5.0.619.

> Why is this so hard?

I'll certainly send a note along to the Illustrator Product Managers, because this is harder than usual.

The short answer is that many Creative Cloud product teams (e.g., Illustrator) are migrating away from using adobeprerelease.com and moving towards distribution via the Creative Cloud Desktop app instead. Illustrator seems to be only partway through the process, making things more complicated.

**Comment by danh525** [comment]
OK, I finally got the prerelease/beta version installed and this did NOT
address our issue. Can you verify that Version 26.0 667 is the version you
think the fix is in? If so, back to the drawing board....

**Comment by sujaisivanandan** [comment]
@danh525 @ErinFinnegan  @zhangusc  the fix is available in Creative Cloud - pre-release section(not the Beta Section). The new pre-release was posted yesterday.

The build with fix is available in Pre-release **26.0.0 Build number 689**

@ErinFinnegan  can you help with the links for getting onto pre-release.

**Comment by ErinFinnegan** [comment]
Hi @danh525 ,

I'm glad to hear that it worked! 😅 A lot of people are waiting on this one. In fact, if you happen to have a lot of users waiting for this, or are at a large Enterprise depending on this fix, it would be helpful to note the estimated impact to the product team.

This build is scheduled for the Adobe MAX timeframe, around October 26-28th. Builds typically roll out to users over a few days across different regions.

**Comment by danh525** [comment]
Hurley is waiting on updating to Big Sur and to CC2021; they are still on
Catalina and CC2020, their motivation is Apple support so Max timeframe
should be good. I can advise our other customers so they don't update too
soon.

**Comment by sujaisivanandan** [comment]
Closing this issue since the fix is available now in Illustrator 26.0(pre-released and to be released at MAX 2021 in Oct).

**Comment by zhangusc** [comment]
@sujaisivanandan Any news from the Illustrator team? We like to know what's Adobe's plan on this issue as we can reproduce the issue on the long-term support version 25.4.2
