### ISSUE TITLE
Illustrator PreRelease 25.3: CSInterface Event Listener never triggered on prerelease while works fine on Beta 25.3 265@236190 

### ISSUE THREAD

**Issue by ghenania** [Adobe-CEP/CEP-Resources#365]
I set up a listener just like this:
```
CSInterface.addEventListener('My Custom Event', function (e) {
  LOG.info("trigged");
});
```

And when I send an event from my JSX like this:
```
try {
    var xLib = new ExternalObject("lib:\\PlugPlugExternalObject");
} catch (e) {
    alert(e);
}

if (xLib) {
    var eventObj = new CSXSEvent();
    eventObj.type = "My Custom Event";
    eventObj.data = "some payload data...";
    eventObj.dispatch();
}
```

this event is never catched when running in PreRelease but works fine in Beta and all other Illustrator older versions since 2015. Any change occurred in PreRelease code that could explain this issue? Our extension is broken :(

Thanks for your support.

**Comment by rushil83** [comment]
var CSLibrary = new CSInterface();

// Listening an event
function addListener(){
CSLibrary.addEventListener('My Custom Event', function (e) {
console.log("Trigged")
});
}

// Adding an Event - 1
function addEvent1() {
var script = 'var mylib = new ExternalObject("lib:" + "PlugPlugExternalObject"); var myObject = new CSXSEvent(); myObject.type = "My Custom Event"; myObject.data = "success"; myObject.dispatch();'
CSLibrary.evalScript(script);
}

// Adding an Event - 2
var event = new CSEvent("My Custom Event", "APPLICATION");
event.data = "This is a test!";
CSLibrary.dispatchEvent(event);


This is the working code for adding and listening to an event.

Questions:
Based on your code it looks like you're following way-1, are you invoking your jsx event script into Evalscript (` CSLibrary.evalScript(script);` ) and where?

**Comment by ghenania** [comment]
@rushil83 Yes Rushil I'm following `way 1`. My event is sent from a JSX script, which is invoked using `CSLibrary.evalScript()` on extension initialization.

**Comment by ghenania** [comment]
@rushil83 to be more precise, the JSX script is invoked by evaluating a minified JSX file just like this:
`CSInterface.evalScript('$.evalFile( "' + jxPath + '")', function (error) {...}`

**Comment by rushilmahajan-adobe** [comment]
Hi @ghenania 
We have faced a similar issue in #364, where the user is not able to execute EvalScript from a cross-site origin Iframe, you can follow this thread for more details.

I create a small extension - [TestEvalScript (link attached)](https://github.com/Adobe-CEP/CEP-Resources/tree/TestEvalScript/CEP_11.x/Samples/TestEvalscript-Cross-Site-IFrame).

1. Main Frame : [Index.html](https://github.com/Adobe-CEP/CEP-Resources/blob/TestEvalScript/CEP_11.x/Samples/TestEvalscript-Cross-Site-IFrame/TestEvalscript/html/index.html) Successfully able to run EvalScript in both Pre-release and Beta
2. [Iframe-1](https://github.com/Adobe-CEP/CEP-Resources/blob/TestEvalScript/CEP_11.x/Samples/TestEvalscript-Cross-Site-IFrame/TestEvalscript/html/sameOriginIframe.html): Created a same-site Iframe I'm successfully able to execute Evalscript in both Pre-Release and Beta
3. [Iframe-2](https://github.com/Adobe-CEP/CEP-Resources/blob/TestEvalScript/CEP_11.x/Samples/TestEvalscript-Cross-Site-IFrame/TestEvalscript/HOST_IFRAME/iframe.html): Created a Cross-site Iframe using chrome [200 OK](https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb?hl=en) hosting [HOST_IFRAME/Iframe.html](https://github.com/Adobe-CEP/CEP-Resources/tree/TestEvalScript/CEP_11.x/Samples/TestEvalscript-Cross-Site-IFrame/TestEvalscript/HOST_IFRAME) at Local Server Point - http://127.0.0.1:8887, **Won't work in Pre-Release, we have to use the workaround- Post-Message mention in #364** 

Please try this extension and In case your problem is different you can fork this Extension(TestEvalScript), apply your changes, and share so we can also repro the issue.

**Comment by rushilmahajan-adobe** [comment]
<img width="1228" alt="TestEval" src="https://user-images.githubusercontent.com/61195208/121363722-d2712b80-c954-11eb-88a7-7dc3a037a5c9.png">

You can run your parsed JSX script and test whether it is working or not in different frames

**Comment by rushilmahajan-adobe** [comment]
@ghenania  
I added an extra frame [(add-event frame)](https://github.com/Adobe-CEP/CEP-Resources/blob/TestEvalScript/CEP_11.x/Samples/TestEvalscript-Cross-Site-IFrame/TestEvalscript/html/addEvent.html) to the same extension. 

Adding a video of successfully addEvent and addListen register event

https://user-images.githubusercontent.com/61195208/121373849-08b2a900-c95d-11eb-9299-7d0e990fa3c2.mov

**Comment by ghenania** [comment]
Thanks @rushilmahajan-adobe, now it works better. 
I don't really understand the difference but it doesn't work when I listen with `window.__adobe_cep__.addEventListener` while it works fine with `CSLibrary.addEventListener`.

**Comment by rushilmahajan-adobe** [comment]
Hi @ghenania 
I tried the `window.__adobe_cep__.addEventListener` in script replacing `CSLibrary.addEventListener` It worked for me in ILST Pre-release.

<img width="1199" alt="Screenshot 2021-06-10 at 1 46 21 PM" src="https://user-images.githubusercontent.com/61195208/121490024-457caf80-c9f2-11eb-87f5-dfa7d20761b3.png">

**Comment by ghenania** [comment]
@rushilmahajan-adobe Ok everything seems good on my side now. I'm closing this issue and we're filing a new issue with @Jolg42 on some new bugs we've found.

**Comment by Jolg42** [comment]
Here is the new issue https://github.com/Adobe-CEP/CEP-Resources/issues/367
