### ISSUE TITLE
Illustrator 25.3 iframe extra security enforcement issue

### ISSUE THREAD

**Issue by malsabbagh** [Adobe-CEP/CEP-Resources#373]
Hey there,

It looks like with Adobe Illustrator 25.3 we have more security enforcement. So Adobe extensions can't host any iframe that has restricted frame-ancestors. This is a problem given Adobe extension is hosted on local machine. I am wondering why this change made it into Adobe Illustrator and not the other Adobe software and what is the future of iframe support for external websites within Adobe in general. This breaks a lot of use cases especially with SSO login within iframes.  

Thanks,

**Comment by sujaisivanandan** [comment]
Hi @malsabbagh, this change is introduced with CEP 11. CEP 11 is being rolled out in Adobe apps and right now Illustrator and Indesign is shipping this. 
You can refer to the migration guides for CEP 11: https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_11.x/Documentation/CEP%2011.1%20HTML%20Extension%20Cookbook.md#migration-from-cep-10-to-cep-11

These changes are due to CEP moving to CEF 88 which has these new changes wrt cross-site iFrames.

**Comment by malsabbagh** [comment]
Thank you @sujaisivanandan, this means we have to implement the same login flows in another modal dialog extension. It is a bit painful to reuse code between web/Adobe when we are not able to use `window.open()`. At least now I know this was done on purpose. 

Thank you again for the info.
