### ISSUE TITLE
Bypass all new restrictions with CEFCommandLine flags

### ISSUE THREAD

**Issue by saar62097** [Adobe-CEP/CEP-Resources#378]
Looks like that adding these two flags in the manifest **bypasses all the new restrictions** of Chromium 88.

```
<Parameter>--disable-site-isolation-trials</Parameter>
<Parameter>--disable-features=SameSiteByDefaultCookies,CookiesWithoutSameSiteMustBeSecure</Parameter>
```
Per [this update](https://www.chromium.org/updates/same-site), it looks like this will work up to Chromium 94, but since CEP11 works with Chromium 88 is it safe to use these two flags and continue with our extensions untouched?

Tested on AfterEffects Prerelease BETA 22.0.0 (build 13)

**Comment by saar62097** [comment]
answer can be found here: https://github.com/Adobe-CEP/CEP-Resources/issues/376

**Comment by Inventsable** [comment]
Thanks! 👍

**Comment by sujaisivanandan** [comment]
Note: Bypassing the restrictions should be treated as a temporary solution only. Extensions should plan for the permanent solution by looking at the cross-site iFrames used.

Also note, adding `<Parameter>--disable-features=SameSiteByDefaultCookies,CookiesWithoutSameSiteMustBeSecure</Parameter>` may break plugins running in CEP 10. In order to have backward compatibility with CEP 10, do add
`<Parameter>--disable-features=SameSiteByDefaultCookies,CookiesWithoutSameSiteMustBeSecure,NetworkService</Parameter>`

**Comment by Inventsable** [comment]
This appears to work in Photoshop and InDesign, but not Illustrator:

```xml
<Parameter>--disable-features=SameSiteByDefaultCookies,CookiesWithoutSameSiteMustBeSecure,NetworkService</Parameter>
```
