### ISSUE TITLE
Illustrator won't reload Html extension when it is closed or hidden.

### ISSUE THREAD

**Issue by hexcola** [Adobe-CEP/CEP-Resources#39]
I wrote a simple extension which support photoshop and illustrator, and didn't set the persistent, when I  update code, then go back to photoshop reopen extension, it's updated, but illustrator not. Is that a bug, or not work on that yet?

**Comment by cameronmcefee** [comment]
I've run into this myself. I have not seen documentation to prove this, but it appears Illustrator is persistent by default (not sure if that can be turned off). If you're using the remote debugging (`.debug` file) method, you can hard refresh (cmd/command + r) in Chrome, which will reload your html panel. If you're using something like livereload in your plugin, this will be effectively the same as non-persistence, as the panel will refresh when you flip back to Illustrator.

However, I've noticed with this method, if you've called an ExtendScript file in your `manifest.mxml` file with `<ScriptPath>./myfile.jsx</ScriptPath>`, this is only initialized at panel startup, so when your panel reloads it will not reload that file. I've gotten around this by omitting ExtendScript files from the manifest and loading them at runtime in the JavaScript like so:

```JavaScript
var CSI = new CSInterface();
var mainJXS = CSI.getSystemPath(SystemPath.EXTENSION) + "/myfile.jsx";
CSI.evalScript( "$.evalFile('" + mainJXS +  "');" );
```

Take note of the single quote in the evalScript string. This is necessary to ensure that the path to the ExtendScript file is passed as a string. Otherwise it'd be evaluated like `(myfile.jsx)` which will throw an error.

**Please note:** I'm writing this about 5 minutes after figuring out that it works. There may be hitches. I've noticed that running `(new File($.fileName)).parent` in the ExtendScript included in the manifest returns a relative path `/` while the ExtendScript included via the `evalScript` method returns the absolute file path. I haven't yet determined if there will be other context-specific ramifications.

**Comment by plugisto** [comment]
This worked for me with Illustrator CC2018.
It is really sad that Adobe / Illustrator team has no motivation to fix this.
(In Photoshop this is no issue)

**Comment by nanmec** [comment]
thank you cameron, i hadn't added any new features to my extension because reloading has been a total drag. this worked for me.
