### ISSUE TITLE
Which license is CEP 11 released under?

### ISSUE THREAD

**Issue by dmitriyyepishin** [Adobe-CEP/CEP-Resources#432]
I do not see license information for CEP 11. Please provide license information so that we can get this library approved by our legal department before using for development.

**Comment by dmitriyyepishin** [comment]
Thanks for replying. The header says "in accordance with the terms of the Adobe license agreement accompanying it". However, there is no accompanying license agreement. In 8.x there is a PDF (https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_8.x/GenSDK_IHC-en_US-20120323_1224.pdf) with a commercial license agreement, but not in 9, 10 or 11.

**Comment by ErinFinnegan** [comment]
Hi there!

So, I spoke with the legal team. Effectively, the 8.x license still the correct license to use for the time being.

We're currently re-working developer touch points and the overall developer experience, including where and how developers use and agree to legal terms. Since it may be several months before we have a new agreement in place, you should continue using the previous terms.

If your legal department wants to follow up, I can put them in touch with the legal team. Reach out to me at finnegan (at) adobe.com (I'm not a lawyer, I work on a developer experience team...)

**Comment by dmitriyyepishin** [comment]
That is a great clarification.
________________________________
